### PR TITLE
Fix metaplugins name to metaPlugins to meet naming convention

### PR DESCRIPTION
**Pull request by Mmduh-483**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
Shall we change the API definition from `metaplugins` to `metaPlugins`? which will align with naming conventions of other fields.

**Comment by Mmduh-483** [comment]
> Shall we change the API definition from `metaplugins` to `metaPlugins`? which will align with naming conventions of other fields.

@zshi-redhat fixed

**Comment by pliurh** [comment]
> > Shall we change the API definition from `metaplugins` to `metaPlugins`? which will align with naming conventions of other fields.
> 
> @zshi-redhat fixed

CRD files in manifests/4.7 shall be updated as well.

**Comment by Mmduh-483** [comment]
> CRD files in manifests/4.7 shall be updated as well.

@zshi-redhat it is already `metaPlugins` 
https://github.com/openshift/sriov-network-operator/blob/master/manifests/4.7/sriov-network-operator-sriovnetwork.crd.yaml#L61

**Pull request merged**
