### PR TITLE
Bug 1914066: Sync to upstream 1-26

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@pliurh looks like some of these commits were already backported?

**Comment by pliurh** [comment]
> @pliurh looks like some of these commits were already backported?

I don't know why github lists those commits in this PR. Here's what I can see from my local branch.

```
# git log --pretty=oneline
261a74ac7ca27768fae267e6975c19fcf3e79b8d (HEAD -> sync, pliurh/sync) Merge branch 'upstream' into sync
ce45f3ccc8e170962f1329b322084528fa7f94fd (npwg/master, upstream) Merge pull request #51 from moshe010/fix_deploy_k8s
7253cae8abd1b282c7f4e123791efc8bd42fa985 add CLUSTER_TYPE=kubernetes to deploy-setup-k8s
4beb329db0b9a9e0aabfe7c1342d40043fb9114d Merge pull request #47 from zshi-redhat/sriov-plugin-node-affinity
4b0bafaa0addf43dddf05f52c650d77e6d6da5e7 nodeAffinity is not correctly updated with DeepDerivative
ed21518f97b5599657339bf00d7ee4bade0ef406 Merge pull request #46 from Mmduh-483/link-type-selector
03736fd9e97b12cca9d74ce5d187f2afc52b4822 Generate device plugin LinkType selector from NodePolicy LinkType
34219822e5425e970a26bdf4278150f63a3f0c1d (origin/release-4.8, origin/release-4.7, origin/master, origin/HEAD, pkg/daemon/daemon.go) Merge pull request #462 from openshift-bot/art-consistency-openshift-4.7-sriov-network-config-daemon
```

**Comment by zshi-redhat** [comment]
> > @pliurh looks like some of these commits were already backported?
> 
> I don't know why github lists those commits in this PR. Here's what I can see from my local branch.
> 
> ```
> # git log --pretty=oneline
> 261a74ac7ca27768fae267e6975c19fcf3e79b8d (HEAD -> sync, pliurh/sync) Merge branch 'upstream' into sync
> ce45f3ccc8e170962f1329b322084528fa7f94fd (npwg/master, upstream) Merge pull request #51 from moshe010/fix_deploy_k8s
> 7253cae8abd1b282c7f4e123791efc8bd42fa985 add CLUSTER_TYPE=kubernetes to deploy-setup-k8s
> 4beb329db0b9a9e0aabfe7c1342d40043fb9114d Merge pull request #47 from zshi-redhat/sriov-plugin-node-affinity
> 4b0bafaa0addf43dddf05f52c650d77e6d6da5e7 nodeAffinity is not correctly updated with DeepDerivative
> ed21518f97b5599657339bf00d7ee4bade0ef406 Merge pull request #46 from Mmduh-483/link-type-selector
> 03736fd9e97b12cca9d74ce5d187f2afc52b4822 Generate device plugin LinkType selector from NodePolicy LinkType
> 34219822e5425e970a26bdf4278150f63a3f0c1d (origin/release-4.8, origin/release-4.7, origin/master, origin/HEAD, pkg/daemon/daemon.go) Merge pull request #462 from openshift-bot/art-consistency-openshift-4.7-sriov-network-config-daemon
> ```

I have to use cherry-pick instead of merge to get clean backport: https://github.com/openshift/sriov-network-operator/pull/465

**Comment by pliurh** [comment]
The problem with using cherry-pick is that the id of the commits will be changed.

**Pull request merged**
