### PR TITLE
Add make fmt before build

### PR DESCRIPTION
**Pull request by Mmduh-483**

### CODE REVIEW

**Comment by Mmduh-483** [comment]
@pliurh any news here?

**Comment by pliurh** [comment]
> @pliurh any news here?

@Mmduh-483 I don't think we shall put the `fmt` in the building targets. Instead I prefer to put this as a requirement in the "how to contribute" section of the README file, and add format validation in openshift CI.

**Comment by Mmduh-483** [comment]
> > @pliurh any news here?
> 
> @Mmduh-483 I don't think we shall put the `fmt` in the building targets. Instead I prefer to put this as a requirement in the "how to contribute" section of the README file, and add format validation in openshift CI.

@pliurh That leads to the same point, where the contributor should run `make fmt`

**Comment by pliurh** [comment]
> > > @pliurh any news here?
> > 
> > 
> > @Mmduh-483 I don't think we shall put the `fmt` in the building targets. Instead I prefer to put this as a requirement in the "how to contribute" section of the README file, and add format validation in openshift CI.
> 
> @pliurh That leads to the same point, where the contributor should run `make fmt`

Yes. The `make fmt` shall be executed before patch get merged, otherwise it cannot pass the CI.

**Comment by Mmduh-483** [comment]
> Yes. The `make fmt` shall be executed before patch get merged, otherwise it cannot pass the CI.

@pliurh I don't see any CI files in the repo, where to add this? isn't it an external CI?

**Comment by pliurh** [comment]
> > Yes. The `make fmt` shall be executed before patch get merged, otherwise it cannot pass the CI.
> 
> @pliurh I don't see any CI files in the repo, where to add this? isn't it an external CI?

The CI code in https://github.com/openshift/release. I haven't got time to work on that yet.

**Comment by pliurh** [comment]
C

**Pull request closed without merging**
