### PR TITLE
Add junit configurations

### PR DESCRIPTION
**Pull request by liornoy**
This PR cherry-picks the addition of the JUnit configuration in the conformance e2e suite,
this is to produce a cleaner report and be aligned with the cnf-tests.

### CODE REVIEW

**Comment by liornoy** [comment]
The failures on the openstack lanes seem not related to this pr

**Comment by SchSeba** [comment]
Hi @liornoy please close this one and open something like https://github.com/openshift/sriov-network-operator/pull/761

**Comment by liornoy** [comment]
> Hi @liornoy please close this one and open something like #761

Done. see https://github.com/openshift/sriov-network-operator/pull/780

**Pull request closed without merging**
