### PR TITLE
Bug 1880990: Fix PF shutdown test. On some nodes route link returns void.

### PR DESCRIPTION
**Pull request by fedepaol**
Here we use another approach to see if the interface is slave of the bridge.
Also, this test proved itself to be pretty dangerous, disabling it in
discovery mode.

Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>

### CODE REVIEW

**Comment by fedepaol** [comment]
/hold
requires validation

**Review by SchSeba — COMMENTED** [review]
/lgtm

/hold

please remove the hold after validation the code looks good!

**Pull request merged**
