### PR TITLE
Add support for Intel X710 Backplane and Base T

### PR DESCRIPTION
**Pull request by vrindle**

### CODE REVIEW

**Comment by vrindle** [comment]
@wizhaoredhat

**Comment by bn222** [comment]
`make bundle manifests` introduces some changes. Let get rid of those, so that the next patch can start from a clean base.

**Comment by bn222** [comment]
vrinda, don't forget to run make bundle manfests after the rebase.

**Comment by wizhaoredhat** [comment]
LGTM

**Pull request merged**
