### PR TITLE
OCPBUGS-15611: Add support for Intel X710 Backplane and Base T

### PR DESCRIPTION
**Pull request by SalDaniele**
Backport https://github.com/openshift/sriov-network-operator/pull/794 to 4.12

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
is this dup with https://github.com/openshift/sriov-network-operator/pull/801 ?

**Comment by wizhaoredhat** [comment]
> is this dup with #801 ?

Yes, because Vrinda is on PTO.

**Comment by SalDaniele** [comment]
@zhaozhanqi Last backport of https://github.com/openshift/sriov-network-operator/pull/794, just need cherry-pick-approved

**Comment by zhaozhanqi** [comment]
> @zhaozhanqi Last backport of #794, just need cherry-pick-approved

sorry for missing your message

**Pull request merged**
