### PR TITLE
OCPBUGS-36734,OCPBUGS-36733,OCPBUGS-36731,OCPBUGS-36730: 4.15 critical bugs

### PR DESCRIPTION
**Pull request by zeeke**
4.15 Backport of:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/711
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/721
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/530
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/700
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/699
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/710
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/720

cc @SchSeba, @mlguerrero12

### CODE REVIEW

**Comment by zeeke** [comment]
/hold

waiting for
- https://github.com/openshift/sriov-network-operator/pull/953

Link the correct jira backports before merging

**Comment by SchSeba** [comment]
Hi @zeeke please remove the func test for mtu that is only for 4.16+ everything else looks good :)

**Comment by zeeke** [comment]
/retitle OCPBUGS-36734,OCPBUGS-36733,OCPBUGS-36731,OCPBUGS-36730: 4.15 critical bugs

**Pull request merged**
