### PR TITLE
BUG 1867529: mellanox plugin - fix resetting unsupported NICs

### PR DESCRIPTION
**Pull request by zshi-redhat**

### CODE REVIEW

**Comment by Mmduh-483** [comment]
@zshi-redhat Did you tested the fix with mellanox nic?

**Comment by zshi-redhat** [comment]
> @zshi-redhat Did you test the fix with mellanox nic?

yes

**Comment by zshi-redhat** [comment]
@pliurh this is likely the issue you hit that switchdev config be reverted automatically.

**Comment by adrianchiris** [comment]
looks good to me.

**Pull request merged**
