### PR TITLE
Set default values for non-required policy fields

### PR DESCRIPTION
**Pull request by zshi-redhat**

### CODE REVIEW

**Comment by pliurh** [comment]
For MTU, if the link_type is IB, shall we also set 1500 as the default value?

**Comment by zshi-redhat** [comment]
> For MTU, if the link_type is IB, shall we also set 1500 as the default value?

From RHEL doc, the common InfiniBand link-layer MTU is 2048.
We always set 1500 in Operator when resetting SR-IOV device for both eth/ib devices, the change in this PR is consistent with current Operator behavior.

For infiniband MTU, I think we can use 2048 as default one. I'll update the pr for webhook, and create a separate one for sriov resetting mtu change.

**Pull request merged**
