### PR TITLE
Bug 2028257: Check if generic_plugin is loaded before invoking it

### PR DESCRIPTION
**Pull request by EmilienM**
(cherry picked from commit 59cbb8b61bdba2b8cb5c2f260cf06913f5ef31ba)

### CODE REVIEW

**Comment by EmilienM** [comment]
@zshi-redhat could you please check why the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2015834) is not ON_QA & verified yet? Anything we can help with?
Thanks

**Comment by zshi-redhat** [comment]
> @zshi-redhat could you please check why the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2015834) is not ON_QA & verified yet? Anything we can help with? Thanks

I duplicated the above bug to bz2028256 which is ON_QA, once it is verified, this PR can be refreshed to get the valid-bug label.

**Pull request merged**
