### PR TITLE
Allow custom nodeSelector for config daemon

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
If `network config daemon` pod is removed from a node, how will it affect the running pod on that node?

**Comment by zshi-redhat** [comment]
Shall `SriovNetworkNodeState` be created only on nodes that run config daemon?

**Comment by pliurh** [comment]
> Shall `SriovNetworkNodeState` be created only on nodes that run config daemon?

good point.

**Comment by pliurh** [comment]
> Shall `SriovNetworkNodeState` be created only on nodes that run config daemon?



> If `network config daemon` pod is removed from a node, how will it affect the running pod on that node?

I don't think there will be any.

**Pull request merged**
