### PR TITLE
Downstream Sync 2023-09-05

### PR DESCRIPTION
**Pull request by liornoy**
This PR syncs with d/s mainly to bring the K8S bump, that is urgent for
resolving a dependency conflict in the cnf-tests.

### CODE REVIEW

**Comment by zeeke** [comment]
Please, use the `merge` sync method instead of `cherry-pick`.

We recently switched to the merge method as:
- It's less error-prone, there is almost no way of forgetting a commit
- It makes downstream commit SHAs to be the same as upstream

**Comment by liornoy** [comment]
@zeeke done

**Comment by zeeke** [comment]
Thanks @liornoy 

/lgtm
/approve

**Pull request merged**
