### PR TITLE
[release-4.3] Bug 1806376: Backport pf partitioning to 4.3

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
Is this commit `7a484bb Fix api version for daemonsets` needed for 4.3? I think we could still use old API version `extentions`.
Do we need to backport SR-IOV Network fix: https://bugzilla.redhat.com/show_bug.cgi?id=1770668 to 4.3?

**Comment by zshi-redhat** [comment]
what about `e25312b Update sriov-network-operator-sriovnetworknodestate.crd.yaml`? It was fixed in the same PR of SR-IOV Partitioning for 4.4.

**Comment by pliurh** [comment]
> Is this commit `7a484bb Fix api version for daemonsets` needed for 4.3? I think we could still use old API version `extentions`.
> Do we need to backport SR-IOV Network fix: https://bugzilla.redhat.com/show_bug.cgi?id=1770668 to 4.3?

This API has already been available since k8s 1.6. So this fix shall also apply to in 4.3.

**Comment by pliurh** [comment]
> what about `e25312b Update sriov-network-operator-sriovnetworknodestate.crd.yaml`? It was fixed in the same PR of SR-IOV Partitioning for 4.4.

We cannot cherry-pick that commit, but yes, we need to do the same thing for 4.3. I've added a new commit for this.

**Pull request merged**
