### PR TITLE
OCPBUGS-36307,OCPBUGS-36308: 416 critical bugs

### PR DESCRIPTION
**Pull request by zeeke**
4.16 Backport of:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/711
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/721

/jira cherrypick OCPBUGS-32139
/jira cherrypick OCPBUGS-36243

cc @SchSeba, @bn222

### CODE REVIEW

**Comment by zeeke** [comment]
/retitle OCPBUGS-36308: OCPBUGS-36307,OCPBUGS-36308: 416 critical bugs

**Comment by SchSeba** [comment]
great work thanks!

/lgtm
/approve

**Pull request merged**
