### PR TITLE
OCPBUGS-20211: update version to 4.15

### PR DESCRIPTION
**Pull request by zeeke**
updated references from 4.14 to 4.15 via:

```
find . -not -path "./vendor*" -type f -print0 | xargs -0 sed -i 's/4\.14/4.15/g'
 make -f Makefile.bundle bundle
```

cc @wizhaoredhat, @bn222

### CODE REVIEW

**Comment by bn222** [comment]
Can you fix some of this manual work? There are places that are hardcoded but we could derive it from a single place where we define the version number.

**Comment by zeeke** [comment]
> Can you fix some of this manual work? There are places that are hardcoded but we could derive it from a single place where we define the version number.

I had a look and I'm not sure where we can improve that, TBH.

Also, this PR images are not doesn't deploying:
[sriov-network-operator.log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_sriov-network-operator/840/pull-ci-openshift-sriov-network-operator-master-operator-e2e/1714204965007790080/artifacts/operator-e2e/gather-extra/artifacts/pods/openshift-sriov-network-operator_sriov-network-operator-979f45b58-dpck6_sriov-network-operator.log)
```
sriov-network-operator: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by sriov-network-operator)
sriov-network-operator: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by sriov-network-operator)
```

I'm investigating

**Comment by bn222** [comment]
https://github.com/openshift/sriov-network-operator/pull/838

**Comment by bn222** [comment]
@zeeke please add OCPBUGS-20211 to the title.

**Comment by zeeke** [comment]
> #838

Missed that, sorry

/retest

**Pull request merged**
