### PR TITLE
Sync deploy/configmap.yaml with 4.10 supported nics

### PR DESCRIPTION
**Pull request by EmilienM**
This will help to use this configmap with support nics in our CI.

### CODE REVIEW

**Comment by SchSeba** [comment]
Hi @EmilienM adding these nics into the list will mean we fully support these nics and I don't think that is the case or what we want to achieve here.

will it be possible as part of your CI system to just add these nics into the configmap after you deploy the operator I think that should be possible.

**Comment by EmilienM** [comment]
> Hi @EmilienM adding these nics into the list will mean we fully support these nics and I don't think that is the case or what we want to achieve here.

Well, the additions in this patch was just a copy paste from `manifests/4.10/supported-nic-ids_v1_configmap.yaml` which _is_ supported. So I don't understand what the issue is. These NICs are already supported, isn't?

> will it be possible as part of your CI system to just add these nics into the configmap after you deploy the operator I think that should be possible.

Yes I can hack but this wasn't my goal.

**Comment by SchSeba** [comment]
Hi @EmilienM I was not aware this was already in the configmap sorry about that :)

can you please open this PR against the u/s repo?
The bundle folder doesn't exist there but the deploy is.

https://github.com/k8snetworkplumbingwg/sriov-network-operator

**Comment by EmilienM** [comment]
> Hi @EmilienM I was not aware this was already in the configmap sorry about that :)
> 
> can you please open this PR against the u/s repo? The bundle folder doesn't exist there but the deploy is.
> 
> https://github.com/k8snetworkplumbingwg/sriov-network-operator

upstream doesn't have `manifests/4.10/supported-nic-ids_v1_configmap.yaml` file, which is why I didn't push it upstream.
Do you want me to sync `manifests/4.10/supported-nic-ids_v1_configmap.yaml` content from downstream to the upstream configmap used in `deploy/` directory?

**Comment by EmilienM** [comment]
any update on this one?

**Comment by EmilienM** [comment]
@SchSeba would you please looking at it again please? Thanks

**Comment by pliurh** [comment]
We have different support NIC list at u/s and d/s. The file in `manifests/4.10/supported-nic-ids_v1_configmap.yaml` will be deployed as part of the operator bundle at d/s.  The file `deploy/configmap.yaml` is only used for local development, so I think it is ok to modify it at both u/s and d/s.

**Comment by EmilienM** [comment]
this PR hasn't got traction, I'll abandon it.

**Pull request closed without merging**
