### PR TITLE
Bug 1774419: Webhook Add validation for resourceName

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
Just to double confirm, do we watch net-attach-def creation and validate resource name in it in operator webhook?

**Comment by pliurh** [comment]
> Just to double confirm, do we watch net-attach-def creation and validate resource name in it in operator webhook? I don;t think we do, right?

No, we don't. Currently, the operator webhook only validates the SriovNetworkNodePolicy CR.

**Pull request merged**
