### PR TITLE
Fix: Operator not applying policy when NumVfs is 0

### LINKED ISSUE #215: Operator is not passing the spec to the vendor plugins when the number of VFs is 0
When create a policy:
```
[root@r-cloudx2-01 sriov-network-operator]# cat policy4-1.yaml 
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy4-1
  namespace: sriov-network-operator
spec:
  nodeSelector:
    kubernetes.io/hostname: r-cloudx2-04
  resourceName: mlxnics41
  priority: 11
  mtu: 9000
  numVfs: 21
  nicSelector:
    vendor: "15b3"
    pfNames: ['enp3s0f1']
    rootDevices: ['0000:03:00.1']
  deviceType: netdevice
  isRdma: true
```
The plugins run and do their work, also when update the `numVfs` to any positive value, but when change it to 0 the plugin doesn't get the `state.Spec`.

I can see that the generic plugin is reacting to the change to 0 and update the number of the VF, but the vendor plugins are not getting this change.

```
I0518 16:23:56.028619   16047 intel_plugin.go:43] intel-plugin OnNodeStateChange()
I0518 16:23:56.028698   16047 mellanox_plugin.go:71] mellanox-Plugin OnNodeStateChange()
I0518 16:23:56.028747   16047 mellanox_plugin.go:80] mellanox-Plugin OnNodeStateChange() state &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:r-cloudx2-04 GenerateName: Namespace:sriov-network-operator SelfLink:/apis/sriovnetwork.openshift.io/v1/namespaces/sriov-network-operator/sriovnetworknodestates/r-cloudx2-04 UID:64b22c46-399a-438f-b25d-c31fee727987 ResourceVersion:1777319 Generation:48 CreationTimestamp:2020-05-18 07:48:12 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[{APIVersion:sriovnetwork.openshift.io/v1 Kind:SriovNetworkNodePolicy Name:default UID:9566b241-fd4a-4260-b147-a1cb42227606 Controller:0xc000ac94ba BlockOwnerDeletion:0xc000ac94b9}] Finalizers:[] ClusterName: ManagedFields:[{Manager:sriov-network-config-daemon Operation:Update APIVersion:sriovnetwork.openshift.io/v1 Time:2020-05-18 16:19:55 +0000 UTC FieldsType:FieldsV1 FieldsV1:&FieldsV1{Raw:*[123 34 102 58 115 116 97 116 117 115 34 58 123 34 46 34 58 123 125 44 34 102 58 105 110 116 101 114 102 97 99 101 115 34 58 123 125 44 34 102 58 115 121 110 99 83 116 97 116 117 115 34 58 123 125 125 125],}} {Manager:sriov-network-operator Operation:Update APIVersion:sriovnetwork.openshift.io/v1 Time:2020-05-18 16:23:55 +0000 UTC FieldsType:FieldsV1 FieldsV1:&FieldsV1{Raw:*[123 34 102 58 109 101 116 97 100 97 116 97 34 58 123 34 102 58 111 119 110 101 114 82 101 102 101 114 101 110 99 101 115 34 58 123 34 46 34 58 123 125 44 34 107 58 123 92 34 117 105 100 92 34 58 92 34 57 53 54 54 98 50 52 49 45 102 100 52 97 45 52 50 54 48 45 98 49 52 55 45 97 49 99 98 52 50 50 50 55 54 48 54 92 34 125 34 58 123 34 46 34 58 123 125 44 34 102 58 97 112 105 86 101 114 115 105 111 110 34 58 123 125 44 34 102 58 98 108 111 99 107 79 119 110 101 114 68 101 108 101 116 105 111 110 34 58 123 125 44 34 102 58 99 111 110 116 114 111 108 108 101 114 34 58 123 125 44 34 102 58 107 105 110 100 34 58 123 125 44 34 102 58 110 97 109 101 34 58 123 125 44 34 102 58 117 105 100 34 58 123 125 125 125 125 44 34 102 58 115 112 101 99 34 58 123 34 46 34 58 123 125 44 34 102 58 100 112 67 111 110 102 105 103 86 101 114 115 105 111 110 34 58 123 125 125 125],}}]} Spec:{DpConfigVersion:1777315 Interfaces:[]} Status:{Interfaces:[{Name:eno1 Mac: Driver:igb PciAddress:0000:01:00.0 Vendor:8086 DeviceID:1521 Mtu:1500 NumVfs:0 LinkSpeed: TotalVfs:7 VFs:[]} {Name:eno2 Mac: Driver:igb PciAddress:0000:01:00.1 Vendor:8086 DeviceID:1521 Mtu:1500 NumVfs:0 LinkSpeed: TotalVfs:7 VFs:[]} {Name:enp3s0f0 Mac: Driver:mlx5_core PciAddress:0000:03:00.0 Vendor:15b3 DeviceID:1017 Mtu:1500 NumVfs:0 LinkSpeed: TotalVfs:21 VFs:[]} {Name:enp3s0f1 Mac: Driver:mlx5_core PciAddress:0000:03:00.1 Vendor:15b3 DeviceID:1017 Mtu:1500 NumVfs:21 LinkSpeed: TotalVfs:21 VFs:[{Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:02.7 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1450 VfID:0} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:03.0 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:1} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:04.1 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:10} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:04.2 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:11} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:04.3 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:12} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:04.4 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:13} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:04.5 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:14} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:04.6 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:15} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:04.7 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1450 VfID:16} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:05.0 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:17} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:05.1 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:18} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:05.2 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:19} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:03.1 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:2} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:05.3 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:20} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:03.2 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1450 VfID:3} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:03.3 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:4} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:03.4 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:5} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:03.5 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1450 VfID:6} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:03.6 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:7} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:03.7 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:8} {Name: Mac: Assigned: Driver:mlx5_core PciAddress:0000:03:04.0 Vendor:15b3 DeviceID:1018 Vlan:0 Mtu:1500 VfID:9}]} {Name:enp129s0 Mac: Driver:mlx4_core PciAddress:0000:81:00.0 Vendor:15b3 DeviceID:1007 Mtu:1500 NumVfs:0 LinkSpeed: TotalVfs:8 VFs:[]}] SyncStatus:Succeeded LastSyncError:}}
I0518 16:23:56.029255   16047 mellanox_plugin.go:178] mellanox-plugin needDrain false needReboot false
I0518 16:23:56.029285   16047 mellanox_plugin.go:179] mellanox-plugin attributes to change: map[]
I0518 16:23:56.029356   16047 generic_plugin.go:80] generic-plugin OnNodeStateChange()
I0518 16:23:56.029422   16047 daemon.go:329] nodeStateChangeHandler(): reqDrain true, reqReboot false
I0518 16:23:56.029446   16047 daemon.go:332] nodeStateChangeHandler(): drain node
I0518 16:23:56.029455   16047 daemon.go:507] drainNode(): Update prepared
```

### PR DESCRIPTION
**Pull request by Mmduh-483**
fixes #215

### CODE REVIEW

**Comment by Mmduh-483** [comment]
@moshe010 @pliurh @adrianchiris

**Comment by zshi-redhat** [comment]
There was issue when setting numVfs to 0: https://bugzilla.redhat.com/show_bug.cgi?id=1814919
Also why do we need to set numVfs to 0?  When VFs are not used, we could always delete the policy which resets numVfs to 0.

**Comment by moshe010** [comment]
> There was issue when setting numVfs to 0: https://bugzilla.redhat.com/show_bug.cgi?id=1814919
> Also why do we need to set numVfs to 0? When VFs are not used, we could always delete the policy which resets numVfs to 0.

But the configuration is not passed to the Mellanox plugin so we can't reset in the FW config to match it.

**Comment by pliurh** [comment]
> > There was issue when setting numVfs to 0: https://bugzilla.redhat.com/show_bug.cgi?id=1814919
> > Also why do we need to set numVfs to 0? When VFs are not used, we could always delete the policy which resets numVfs to 0.
> 
> But the configuration is not passed to the Mellanox plugin so we can't reset in the FW config to match it.

When `OnNodeStateChange` is invoked, the config daemon will pass both the new and old CR of the SriovNetworkNodeState. You can use that to tell if an interface needs to be reset.

**Comment by moshe010** [comment]
> > > There was issue when setting numVfs to 0: https://bugzilla.redhat.com/show_bug.cgi?id=1814919
> > > Also why do we need to set numVfs to 0? When VFs are not used, we could always delete the policy which resets numVfs to 0.
> > 
> > 
> > But the configuration is not passed to the Mellanox plugin so we can't reset in the FW config to match it.
> 
> When `OnNodeStateChange` is invoked, the config daemon will pass both the new and old CR of the SriovNetworkNodeState. You can use that to tell if an interface needs to be reset.

ok got it

**Comment by pliurh** [comment]
Close this PR, as we decided to keep current behavior.

**Pull request closed without merging**
