### PR TITLE
Sync master 14 09 22

### PR DESCRIPTION
**Pull request by wizhaoredhat**

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
@zshi-redhat @bn222 @SchSeba @zeeke FYI

**Comment by bn222** [comment]
Support external control plane is actually part of a PR I'm working on (watiing for 1 more PR to get merged upstream). Please keep that one separate.

**Comment by wizhaoredhat** [comment]
> Support external control plane is actually part of a PR I'm working on (waiting for 1 more PR to get merged upstream). Please keep that one separate.

@bn222
Done, Dropped the "support external control plane" commit made by Zenghui.

**Pull request merged**
