### PR TITLE
Bug 1921321: Sync upstream 2021-4-6

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
Please exclude this commit: `Enable hugepage injection in network resources injector ` at this moment.
The commit depends on https://github.com/openshift/cluster-kube-apiserver-operator/pull/1080 which hasn't merged yet.

**Comment by dougbtv** [comment]
Just a quick note that https://github.com/openshift/cluster-kube-apiserver-operator/pull/1080 merged :+1:

**Pull request merged**
