### PR TITLE
OCPBUGS-22279: [release-4.14] virtual: get real PCI address for each device found

### PR DESCRIPTION
**Pull request by zeeke**
cc @EmilienM

### CODE REVIEW

**Comment by EmilienM** [comment]
@zeeke @SchSeba FYI when patching the supported NICs ConfigMap, it doesn't seem to be applied when the operator is deployed in CI.
Let me know if you have any idea before I dig into this.

Thanks

**Comment by EmilienM** [comment]
@zivgreenberg for review. Thanks

**Comment by EmilienM** [comment]
Check: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_sriov-network-operator/843/pull-ci-openshift-sriov-network-operator-release-4.14-e2e-openstack-nfv-hwoffload/1716506502799298560/artifacts/e2e-openstack-nfv-hwoffload/gather-extra/artifacts/configmaps.json
We can see that the new device is missing from `supported-nic-ids`.

**Comment by EmilienM** [comment]
I found it, it's because the downstream fork also uses `manifests/stable/supported-nic-ids_v1_configmap.yaml` and when @zeeke applied the cherry-pick, we forgot to update this file.

**Comment by zeeke** [comment]
/hold

waiting
- https://github.com/openshift/sriov-network-operator/pull/844

**Comment by EmilienM** [comment]
@zeeke please backport the virtio fix in this PR, so later I can use this PR to backport to 4.13 and older. Thanks a lot

**Comment by zeeke** [comment]
/label backport-risk-assessed

@zhaozhanqi, @EmilienM we need `cherry-pick-approved labels` here: do you know who can help on OpenStack related PRs?

**Comment by EmilienM** [comment]
@eurijon @zivgreenberg

**Comment by mandre** [comment]
This needs the staff-eng-approved for merging the urgent fix to 4.14.
/assign @knobunc

**Comment by EmilienM** [comment]
4.13 backport: https://github.com/openshift/sriov-network-operator/pull/852

**Pull request merged**
