### PR TITLE
BUG 1773840: Prepare operator bundle for 4.3

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
shall we also apply version changes to below files:
```
./deploy/operator.yaml:              value: 0.0.1-snapshot
./hack/env.sh:export RELEASE_VERSION=0.0.1-snapshot
./manifests/4.3/sriov-network-operator.v0.0.1.clusterserviceversion.yaml:                      value: 0.0.1
./manifests/4.4/sriov-network-operator.v0.0.1.clusterserviceversion.yaml:                      value: 0.0.1
```

**Comment by pliurh** [comment]
> shall we also apply version changes to below files:
> 
> ```
> ./deploy/operator.yaml:              value: 0.0.1-snapshot
> ./hack/env.sh:export RELEASE_VERSION=0.0.1-snapshot
> ./manifests/4.3/sriov-network-operator.v0.0.1.clusterserviceversion.yaml:                      value: 0.0.1
> ./manifests/4.4/sriov-network-operator.v0.0.1.clusterserviceversion.yaml:                      value: 0.0.1
> ```

fixed.

**Pull request merged**
