### PR TITLE
Bump master to version 4.6

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
I didn't see a file under `manifests/4.6/sriov-network-operator.v4.6.0.clusterserviceversion.yaml`
Is it not required any more ?

**Comment by pliurh** [comment]
> I didn't see a file under `manifests/4.6/sriov-network-operator.v4.6.0.clusterserviceversion.yaml`
> Is it not required any more ?

Added.

**Pull request merged**
