### PR TITLE
Bug 1841042: [Release 4.4] Make the daemon more resilient to failures.

### PR DESCRIPTION
**Pull request by fedepaol**
When the get nodes in uncordon fails, the daemon exits and the node remains uncordoned.
When the get of the device plugin pod fails, the daemon does not restart it and the
change requested does not get applied.

This is a manual cherry pick of https://github.com/openshift/sriov-network-operator/pull/222

### CODE REVIEW

**Comment by fedepaol** [comment]
/bugzilla refresh

Picky bot!

**Comment by mfojtik** [comment]
@pliurh @fedepaol this needs approved label before I can cherry pick approve it.

**Pull request merged**
