### PR TITLE
feat: added leader election conventons

### PR DESCRIPTION
**Pull request by eggfoobar**
This should take advantage of leader election changes for SNO clusters proposed in this [library-go PR](https://github.com/openshift/library-go/pull/1242).

Changes:
  - updated leader election to follow convention and use SNO topology aware methods
  - updated openshift/client-go and openshift/api

ran:
go mod tidy && go mod vendor

Signed-off-by: ehila <ehila@redhat.com>

### CODE REVIEW

**Comment by pliurh** [comment]
@eggfoobar Thanks for your PR. We have an upstream project at https://github.com/k8snetworkplumbingwg/sriov-network-operator. Could you propose the change there?

**Comment by SchSeba** [comment]
+1 please open the PR on the u/s repo so we can have a discussion there.

**Comment by eggfoobar** [comment]
Sure thing

**Pull request closed without merging**
