### PR TITLE
Set logLevel to 2 when recreating default SriovOperatorConfig

### PR DESCRIPTION
**Pull request by zshi-redhat**

### CODE REVIEW

**Comment by SchSeba** [comment]
we have the creation when the operator starts here https://github.com/openshift/sriov-network-operator/blob/master/cmd/manager/main.go#L148

This change is only in case someone remove the `default` object right?

**Comment by zshi-redhat** [comment]
> we have the creation when the operator starts here https://github.com/openshift/sriov-network-operator/blob/master/cmd/manager/main.go#L148
> 
> This change is only in case someone remove the `default` object right?

yes, just make sure the re-created sriovOperatorConfig has the right value for LogLevel

**Pull request merged**
