### PR TITLE
Add support for OpenStack metadata

### PR DESCRIPTION
**Pull request by atyronesmith**
[Addresses Issue](https://github.com/openshift/sriov-network-operator/issues/399)

When OpenShift is deployed on OpenStack, OpenStack provides additional metadata about networks that can be used by the sriov-network-operator. This metadata specifies which OpenStack networks (UUID) are connected to which interface of the VM. In addition, if Device Role Tagging is used, the metadata can also provide labels that allow the grouping of VF resources.

### CODE REVIEW

**Comment by atyronesmith** [comment]
Accidental closure....

**Comment by zshi-redhat** [comment]
@atyronesmith  talking to Peng, it might be good to have a generic name for the new selector that can be used across multiple platforms (e.g. vmware, baremetal if needed). do you know if there are equivalent feature in vmware or any other cloud providers for device tagging, device IDs metadata? what are the names used in those platforms?

**Comment by atyronesmith** [comment]
> @atyronesmith talking to Peng, it might be good to have a generic name for the new selector that can be used across multiple platforms (e.g. vmware, baremetal if needed). do you know if there are equivalent feature in vmware or any other cloud providers for device tagging, device IDs metadata? what are the names used in those platforms?

Good point.  Let me check.

**Comment by zshi-redhat** [comment]
> > @atyronesmith talking to Peng, it might be good to have a generic name for the new selector that can be used across multiple platforms (e.g. vmware, baremetal if needed). do you know if there are equivalent feature in vmware or any other cloud providers for device tagging, device IDs metadata? what are the names used in those platforms?
> 
> Good point. Let me check.

In case we don't know what other platforms may support, I think having either one of `networkID` or `networkTag` would be sufficient for openstack VM case, @atyronesmith wdyt? In this PR, we can leave one and remove the other the minimize the API change.

**Comment by atyronesmith** [comment]
> > > @atyronesmith talking to Peng, it might be good to have a generic name for the new selector that can be used across multiple platforms (e.g. vmware, baremetal if needed). do you know if there are equivalent feature in vmware or any other cloud providers for device tagging, device IDs metadata? what are the names used in those platforms?
> > 
> > 
> > Good point. Let me check.
> 
> In case we don't know what other platforms may support, I think having either one of `networkID` or `networkTag` would be sufficient for openstack VM case, @atyronesmith wdyt? In this PR, we can leave one and remove the other the minimize the API change.

How about just infraNet  and have it either be a UUID or a tag?

**Comment by zshi-redhat** [comment]
> > > > @atyronesmith talking to Peng, it might be good to have a generic name for the new selector that can be used across multiple platforms (e.g. vmware, baremetal if needed). do you know if there are equivalent feature in vmware or any other cloud providers for device tagging, device IDs metadata? what are the names used in those platforms?
> > > 
> > > 
> > > Good point. Let me check.
> > 
> > 
> > In case we don't know what other platforms may support, I think having either one of `networkID` or `networkTag` would be sufficient for openstack VM case, @atyronesmith wdyt? In this PR, we can leave one and remove the other the minimize the API change.
> 
> How about just infraNet and have it either be a UUID or a tag?

Does the `Infra` here refer to platform infra such as openstack, vmware etc?

**Comment by atyronesmith** [comment]
> > > > > @atyronesmith talking to Peng, it might be good to have a generic name for the new selector that can be used across multiple platforms (e.g. vmware, baremetal if needed). do you know if there are equivalent feature in vmware or any other cloud providers for device tagging, device IDs metadata? what are the names used in those platforms?
> > > > 
> > > > 
> > > > Good point. Let me check.
> > > 
> > > 
> > > In case we don't know what other platforms may support, I think having either one of `networkID` or `networkTag` would be sufficient for openstack VM case, @atyronesmith wdyt? In this PR, we can leave one and remove the other the minimize the API change.
> > 
> > 
> > How about just infraNet and have it either be a UUID or a tag?
> 
> Does the `Infra` here refer to platform infra such as openstack, vmware etc?

Yes.  it could be called netFilter as well...

**Comment by zshi-redhat** [comment]
> > > > > > @atyronesmith talking to Peng, it might be good to have a generic name for the new selector that can be used across multiple platforms (e.g. vmware, baremetal if needed). do you know if there are equivalent feature in vmware or any other cloud providers for device tagging, device IDs metadata? what are the names used in those platforms?
> > > > > 
> > > > > 
> > > > > Good point. Let me check.
> > > > 
> > > > 
> > > > In case we don't know what other platforms may support, I think having either one of `networkID` or `networkTag` would be sufficient for openstack VM case, @atyronesmith wdyt? In this PR, we can leave one and remove the other the minimize the API change.
> > > 
> > > 
> > > How about just infraNet and have it either be a UUID or a tag?
> > 
> > 
> > Does the `Infra` here refer to platform infra such as openstack, vmware etc?
> 
> Yes. it could be called netFilter as well...

netFilter sounds better than infraNet in my opinion.
@pliurh wdyt

**Comment by pliurh** [comment]
Additionally, we can use a formated string `<platform>/<metadata>:<id>` to make this flag more user friendly, e.g. `openstack/NetworkID:xxxxx-xxxx-xxxx'.

**Comment by atyronesmith** [comment]
> Additionally, we can use a formated string `<platform>/<metadata>:<id>` to make this flag more user-friendly, e.g. `openstack/NetworkID:xxxxx-xxxx-xxxx`.

Yes.  That was my original thought.  However, in general, kubernetes API "doctrine" seems to frown upon "non-well defined" fields.  If you think the above is acceptable, then a more general field would be good.

**Comment by pliurh** [comment]
> > Additionally, we can use a formated string `<platform>/<metadata>:<id>` to make this flag more user-friendly, e.g. `openstack/NetworkID:xxxxx-xxxx-xxxx`.
> 
> Yes. That was my original thought. However, in general, kubernetes API "doctrine" seems to frown upon "non-well defined" fields. If you think the above is acceptable, then a more general field would be good.

Another option is to use `runtime.RawExtension` instead of `string` for this field. This is a way to embed other APIs in a CRD.

**Comment by zshi-redhat** [comment]
> > > Additionally, we can use a formated string `<platform>/<metadata>:<id>` to make this flag more user-friendly, e.g. `openstack/NetworkID:xxxxx-xxxx-xxxx`.
> > 
> > 
> > Yes. That was my original thought. However, in general, kubernetes API "doctrine" seems to frown upon "non-well defined" fields. If you think the above is acceptable, then a more general field would be good.
> 
> Another option is to use `runtime.RawExtension` instead of `string` for this field. This is a way to embed other APIs in a CRD.

@pliurh @atyronesmith 
Should this be discussed later when we have a clear understanding of how other cloud providers are passing network metadata info?  I felt we can start from a simple string value that could already satisfy the need of openstack.

**Comment by atyronesmith** [comment]
I have pushed a commit that contains only a single field, NetFilter.  The netFilter has the format described above: openstack/NetworkID:UUID.  The nodestate shows the netFilter in the format and the nodepolicy can be specified with the format.  
/cc @zshi-redhat @pliurh

**Comment by atyronesmith** [comment]
The PM has agreed that the additional Tag information would cause more confusion than additional value and therefore has been removed.

**Comment by pliurh** [comment]
looks good to me. @zshi-redhat PTAL

**Pull request merged**
