### PR TITLE
Create manifests for 4.7

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
Why the old version manifests are removed from master?

**Comment by pliurh** [comment]
> Why the old version manifests are removed from master?

The old version folders are only consumed by ART on the specific branch.

**Comment by zshi-redhat** [comment]
> > Why the old version manifests are removed from master?
> 
> The old version folders are only consumed by ART on the specific branch.

In case there is a bug in the manifests for released branch, do we need to merge the fix in master branch, then backport all the way to the specific branch?

**Comment by pliurh** [comment]
> > > Why the old version manifests are removed from master?
> > 
> > 
> > The old version folders are only consumed by ART on the specific branch.
> 
> In case there is a bug in the manifests for released branch, do we need to merge the fix in master branch, then backport all the way to the specific branch?

I don't think we need to.

**Pull request merged**
