### PR TITLE
[Downstream] Add new DPU/Accelerator NICs

### PR DESCRIPTION
**Pull request by wizhaoredhat**
We are adding the Intel NetSec Accelerator and Marvell Octeon 10 DPU

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
@bn222 @SchSeba  PTAL at these DPU/Accelerator NICs that we are supporting.

**Comment by bn222** [comment]
use merge bot instead? ie. just wait?

**Comment by bn222** [comment]
Or is this downstream only?

**Comment by wizhaoredhat** [comment]
> Or is this downstream only?

Downstream only.

**Pull request merged**
