### PR TITLE
OCPBUGS-5210: Fix passing device to mstconfig

### PR DESCRIPTION
**Pull request by bn222**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
Do we have a master fix in place? If not, there will be dependency issue with bugzilla reference.

**Comment by zshi-redhat** [comment]
> Do we have a master fix in place? If not, there will be dependency issue with bugzilla reference.

ignore this, I just noticed there is another PR for master.

**Comment by zhaozhanqi** [comment]
`Needs bugzilla/valid-bug label`

@bn222  this may need a jira issue for this PR in order to merge it

**Comment by SchSeba** [comment]
Hi @bn222 can you please wait for the master to get merged and then request a cherry-pick from the bot.
you will also need to create a jira bug for 4.13 pointing to master then the bot will create everything you need for the backport

**Pull request merged**
