### PR TITLE
Bug 2101525: add Intel E810 NIC model (1591) support in SR-IOV Operator

### PR DESCRIPTION
**Pull request by novacain1**
Upstream merged commit: https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/326

The Intel series of E810 cards with a 1591 PF ID need to be added to the supported card listing in OpenShift. This PCI ID belongs to [Intel.](https://www.pcilookup.com/?ven=8086&dev=1591&action=submit)

Cards have Vendor ID 8086, PF 1591, and VF of 1889.

Note: Silicom TimeSync cards (STS2, STS4, etc) contain this embedded E810 in those particular network adapters.

Cards were tested internally in Red Hat and found to be passing. Request of this PR is to get them to the supported list of devices.

### CODE REVIEW

**Comment by bn222** [comment]
This is a backport of https://github.com/k8snetworkplumbingwg/sriov-network-operator/commit/37b62c5cdb0fe4d80c8496a173983c594205bb06

I prefer the upstream commit message. Why is the commit message different in this downstream commit?

**Comment by novacain1** [comment]
> This is a backport of [k8snetworkplumbingwg/sriov-network-operator@37b62c5](https://github.com/k8snetworkplumbingwg/sriov-network-operator/commit/37b62c5cdb0fe4d80c8496a173983c594205bb06)
> 
> I prefer the upstream commit message. Why is the commit message different in this downstream commit?

Modified.

**Comment by SchSeba** [comment]
/hold

I will like to open this one in a sync PR I am working on

**Comment by bn222** [comment]
@SchSeba I prefer to have it as a separate PR. The sync PR can have the other commits. Is there a real reason to have it be part of the sync PR?

**Comment by SchSeba** [comment]
sounds good @bn222 

/hold cancel

**Comment by SchSeba** [comment]
LGTM

**Pull request merged**
