### PR TITLE
OCPBUGS-23795: Downstream merge Sync/20240822

### PR DESCRIPTION
**Pull request by zeeke**
Downstream sync PR via `git merge`. Relevant commit is:
- 1183e4f40949ef7ad05007e4e6abe424a1c9ed1d

All other commits appears here because the previous sync had modified the history:
- https://github.com/openshift/sriov-network-operator/pull/990

### CODE REVIEW

**Review by SchSeba — APPROVED** [review]
/lgtm
/approve

**Comment by SchSeba** [comment]
/hold

lets get time for the CI to run

**Comment by zeeke** [comment]
`ci/prow/e2e-telco5g-sriov` job fails to rebase this PR on master. 

```
+ [[ -n 992 ]]
+ [[ sriov-network-operator == \s\r\i\o\v\-\n\e\t\w\o\r\k\-\o\p\e\r\a\t\o\r ]]
+ git fetch upstream pull/992/head
From https://github.com/openshift/sriov-network-operator
 * branch                refs/pull/992/head -> FETCH_HEAD
+ git checkout -b pr-992 FETCH_HEAD
Switched to a new branch 'pr-992'
+ git pull --rebase upstream master
From https://github.com/openshift/sriov-network-operator
 * branch                master     -> FETCH_HEAD
Rebasing (1/9)
dropping f8cc3364c9a16d42a6669[68](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_sriov-network-operator/992/pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov/1826617492148064256#1:build-log.txt%3A68)dff90dbfbf7219260 Remove logic that installs rdma-core package -- patch contents already upstream
Rebasing (2/9)
Auto-merging bindata/manifests/daemon/daemonset.yaml
CONFLICT (content): Merge conflict in bindata/manifests/daemon/daemonset.yaml
Auto-merging bindata/manifests/operator-webhook/server.yaml
Auto-merging bindata/manifests/webhook/server.yaml
Auto-merging config/manager/manager.yaml
CONFLICT (content): Merge conflict in config/manager/manager.yaml
Auto-merging deploy/operator.yaml
Auto-merging deployment/sriov-network-operator-chart/templates/operator.yaml
error: could not apply 7c592c52f... manifests: set required-scc for openshift workloads
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 7c5[92](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_sriov-network-operator/992/pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov/1826617492148064256#1:build-log.txt%3A92)c52f... manifests: set required-scc for openshift workloads
```

Merging this as there is no quick way to make that rebase work (this PR is merging some already cherry-picked commits). I'm going to propose a fix in the `openshift/release` repo to avoid rebasing. It would be also good to avoid building the operator again and use CI promoted images.

/hold cancel

**Pull request merged**
