### PR TITLE
Sync k8snetworkplumbingwg/master 2022_09_22

### PR DESCRIPTION
**Pull request by zeeke**
Gather commits using

```
$ git --no-pager log --cherry-pick --format="%h %s" --left-only --no-merges upstream/master...openshift/master
42eb7e94 Fix the issue introduced in https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/240/files#r808624002
34b3fc31 move mellanox mstconfig functions to the utils_mlx.go
3a2ee559 update yaml configuration to allow for control plane status detection
64a59431 add automation path for components to operate in a hypershift environment (without mco)
9ca96bc9 add openshift context struct for openshift specific metadata
6cdb4827 improve drain check
61a08207 Adding suport for Octeon DPU family
c3fd5f64 update openshift-api to include external control plane topology enum
711302e0 support external control plane

c5c69732 lint: fix goconst issues
...

$ git cherry-pick 711302e0 c3fd5f64 61a08207 6cdb4827 9ca96bc9 64a59431 3a2ee559 34b3fc31 42eb7e94
```

/cc @SchSeba

### CODE REVIEW

**Comment by bn222** [comment]
Please exclude the patches coming in with https://github.com/openshift/sriov-network-operator/pull/702

**Comment by zeeke** [comment]
> Please exclude the patches coming in with #702

Done

**Comment by zeeke** [comment]
@zshi-redhat can please have a look at this d/s sync?
If there is no objection, I'll remove the `hold` label

**Comment by bn222** [comment]
/remove hold

@zshi-redhat will not be able to review this this week

**Comment by zeeke** [comment]
/unhold

ok

**Pull request merged**
