### PR TITLE
wip(x520): adding support for X520 dual-10G DA/SFP+

### PR DESCRIPTION
**Pull request by faust64**
Purely theoretical, although based on successful tests on 4.1, involving openshift/sriov-network-device-plugin#16

### CODE REVIEW

**Comment by fepan** [comment]
There is no current plan to support X520.

**Comment by pliurh** [comment]
@fepan shall we be open to this in upstream if there're people want to contribute? We can still claim that we don't support it downstream.

> There is no current plan to support X520.

**Comment by faust64** [comment]
Indeed, refusing contributions to an opensource project because "there's no plan to support X" doesn't make much sense. Or at least, goes against the "upstream first" approach.

I'm sure the average OKD user don't care much about which devices would be supported, should they go with OCP.
While the only OCP 4 customer I've met so far was wondering: why would we need card-by-card approval?

I'm sure there would be some discrepancies from vendor to vendor, still I doubt the X520 chip from Intel varies much from that X710 one we're supporting already.
IMHO, considering most OCP 4.x customers are only evaluating OpenShift 4, it might be better not to limit them right away, rather encourage them in giving us some feedback for cases that were not otherwise validated. Which might even help in cherry-picking whichever new devices to support in future releases.

**Comment by fepan** [comment]
The whitelist behavior is only implemented downstream for support reasons. There is no restriction on upstream as to which NIC is used.

**Comment by eparis** [comment]
at this moment PRs should be sent to master, not to release-4.2. I believe this should be closed...

**Comment by fepan** [comment]
We have no plan to implement this feature at this time. Closing.

**Pull request closed without merging**
