### PR TITLE
Add Nvidia device ID 15b3/101f/101e

### PR DESCRIPTION
**Pull request by zshi-redhat**
Signed-off-by: Zenghui Shi <zshi@redhat.com>

### CODE REVIEW

**Comment by SchSeba** [comment]
should we also open a PR to change it here?

https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/deploy/configmap.yaml#L19

**Comment by zshi-redhat** [comment]
> should we also open a PR to change it here?
> 
> https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/deploy/configmap.yaml#L19

We take different approach tracking supported NICs downstream.

**Pull request merged**
