### PR TITLE
[release-4.10] Bug 2072038: backport leader election for sno to 4.10

### PR DESCRIPTION
**Pull request by eggfoobar**

### CODE REVIEW

**Comment by SchSeba** [comment]
Hi @eggfoobar the PR is failing because the RBAC is not part of the CSV. 
you need to configure the RBAC in config/rbac folder and then generate the bundle that should add them to the CSV file

**Comment by SchSeba** [comment]
@zshi-redhat @pliurh can you please add the label I don't have permission to do it

**Comment by eggfoobar** [comment]
@SchSeba is there anything else missing for this PR to go through?

**Pull request merged**
