### PR TITLE
Bug 1756471: Add operator bundle for 4.3

### LINKED ISSUE #82: olm data needs to be updated for 4.3
https://github.com/openshift/sriov-network-operator/tree/release-4.3/manifests/4.2
file not found: manifests/4.3/image-references

### PR DESCRIPTION
**Pull request by pliurh**
Fix #82

### CODE REVIEW

**Comment by jupierce** [comment]
I think the convention is also to delete the old 4.2 data.

**Comment by pliurh** [comment]
> I think the convention is also to delete the old 4.2 data.

If del

**Comment by pliurh** [comment]
> I think the convention is also to delete the old 4.2 data.

Deleted.

**Pull request merged**
