### PR TITLE
OCPBUGS-22807: Hash contents of cm instead of using resource version

### PR DESCRIPTION
**Pull request by bn222**

### CODE REVIEW

**Comment by bn222** [comment]
Not a clean backport. Needed to make sure that `r.syncSriovNetworkNodeState` was called correctly. The change is trivial.

**Comment by wizhaoredhat** [comment]
> Not a clean backport. Needed to make sure that `r.syncSriovNetworkNodeState` was called correctly. The change is trivial.

I see it, it is that the function is missing ctx in `r.syncSriovNetworkNodeState(ctx, np, npl, ns, &node, utils.HashConfigMap(found));`

**Pull request merged**
