### PR TITLE
OCPBUGS-5178: Fix passing device to mstconfig

### PR DESCRIPTION
**Pull request by bn222**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
/lgtm
downstream only fix.

**Comment by EmilienM** [comment]
@bn222 e2e jobs fail for the same reason:
```
 Timed out waiting for the catalog source oo-pf7fs to become ready after 10 minutes. 
```

Sounds like unrelated to this patch, and it affects all e2e (not only OpenStack).

**Comment by zshi-redhat** [comment]
Operator installation failed in the operator-e2e test, I wonder if it is due to 4.13 sriov operator catalog not ready for testing in CI. (operator-e2e test passes in the 4.12 PR).

**Comment by bn222** [comment]
> Operator installation failed in the operator-e2e test, I wonder if it is due to 4.13 sriov operator catalog not ready for testing in CI. (operator-e2e test passes in the 4.12 PR).

This is what I was thinking too. I think it might make sense to bypass the bot to get this one in before 4.13 catalogue becomes available.

**Comment by bn222** [comment]
We will know after GA date. If the issue disappears by then,  the we know why. we already have something in jira to track that we need to address a related issue.

**Pull request merged**
