### PR TITLE
Do Not Merge: testing switchdev implementation

### PR DESCRIPTION
**Pull request by zeeke**
Testing PR for:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/750

### CODE REVIEW

**Comment by sshnaidm** [comment]
> During validation test, one webhook pod out of 3 is not able to start because of an ImagePullBackoff error:
> 
> ```
> openshift-sriov-network-operator                   24m         Warning   Failed                                        pod/operator-webhook-9f8kw                                                         Failed to pull image "image-registry.openshift-image-registry.svc:5000/openshift-sriov-network-operator/sriov-network-webhook:latest": reading manifest latest in image-registry.openshift-image-registry.svc:5000/openshift-sriov-network-operator/sriov-network-webhook: authentication required
> ```
> 
> https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_sriov-network-operator/981/pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov/1822899499446571008/artifacts/e2e-telco5g-sriov/gather-extra/artifacts/oc_cmds/events
> 
> /test e2e-telco5g-sriov

It happened before, seems like race condition. @SchSeba can we do something for it? To wait, restart, redeploy or something.

**Comment by zeeke** [comment]
> > During validation test, one webhook pod out of 3 is not able to start because of an ImagePullBackoff error:
> > ```
> > openshift-sriov-network-operator                   24m         Warning   Failed                                        pod/operator-webhook-9f8kw                                                         Failed to pull image "image-registry.openshift-image-registry.svc:5000/openshift-sriov-network-operator/sriov-network-webhook:latest": reading manifest latest in image-registry.openshift-image-registry.svc:5000/openshift-sriov-network-operator/sriov-network-webhook: authentication required
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_sriov-network-operator/981/pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov/1822899499446571008/artifacts/e2e-telco5g-sriov/gather-extra/artifacts/oc_cmds/events
> > /test e2e-telco5g-sriov
> 
> It happened before, seems like race condition. @SchSeba can we do something for it? To wait, restart, redeploy or something.

Validation suite is run repeatedly, around 72 times. ([job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_sriov-network-operator/981/pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov/1822899499446571008#1:build-log.txt%3A1612)) 

There must be something on the node :thinking: :
([image-registry.log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_sriov-network-operator/981/pull-ci-openshift-sriov-network-operator-master-e2e-telco5g-sriov/1822899499446571008/artifacts/e2e-telco5g-sriov/gather-extra/artifacts/pods/openshift-image-registry_image-registry-75df7f7947-hkf6g_registry.log))
```
time="2024-08-12T09:26:48.214745521Z" level=info msg=response go.version="go1.22.5 (Red Hat 1.22.5-1.el9) X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=aba49591-d4e4-4f26-86de-8e873aaaa66e http.request.method=GET http.request.remoteaddr="100.64.0.3:53166" http.request.uri="/openshift/token?scope=repository%3Aopenshift-sriov-network-operator%2Fsriov-network-webhook%3Apull" http.request.useragent="cri-o/1.30.4 os/linux arch/amd64" http.response.contenttype=application/json http.response.duration="71.769µs" http.response.status=200 http.response.written=49
time="2024-08-12T09:26:48.216853084Z" level=error msg="OpenShift client error: selfsubjectaccessreviews.authorization.k8s.io is forbidden: User \"system:anonymous\" cannot create resource \"selfsubjectaccessreviews\" in API group \"authorization.k8s.io\" at the cluster scope" go.version="go1.22.5 (Red Hat 1.22.5-1.el9) X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=717ea966-1f4e-464e-b51a-82807cf415c3 http.request.method=GET http.request.remoteaddr="100.64.0.3:53166" http.request.uri=/v2/openshift-sriov-network-operator/sriov-network-webhook/manifests/latest http.request.useragent="cri-o/1.30.4 os/linux arch/amd64" openshift.auth.user=anonymous vars.name=openshift-sriov-network-operator/sriov-network-webhook vars.reference=latest
time="2024-08-12T09:26:48.224357979Z" level=warning msg="error authorizing context: access denied" go.version="go1.22.5 (Red Hat 1.22.5-1.el9) X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=717ea966-1f4e-464e-b51a-82807cf415c3 http.request.method=GET http.request.remoteaddr="100.64.0.3:53166" http.request.uri=/v2/openshift-sriov-network-operator/sriov-network-webhook/manifests/latest http.request.useragent="cri-o/1.30.4 os/linux arch/amd64" vars.name=openshift-sriov-network-operator/sriov-network-webhook vars.reference=latest
time="2024-08-12T09:26:48.224405927Z" level=info msg=response go.version="go1.22.5 (Red Hat 1.22.5-1.el9) X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=240079de-af3c-43aa-a52e-46524194a5fc http.request.method=GET http.request.remoteaddr="100.64.0.3:53166" http.request.uri=/v2/openshift-sriov-network-operator/sriov-network-webhook/manifests/latest http.request.useragent="cri-o/1.30.4 os/linux arch/amd64" http.response.contenttype=application/json http.response.duration=9.27561ms http.response.status=401 http.response.written=197
```

**Pull request closed without merging**
