### PR TITLE
Bump up operator version to 4.10

### PR DESCRIPTION
**Pull request by pliurh**

### CODE REVIEW

**Comment by pliurh** [comment]
The operator-e2e job uses the origin image https://quay.io/repository/openshift/origin-sriov-network-operator. The 4.10 image of which is not mirrored to the latest/master image yet. So that job keeps failing.

**Comment by pliurh** [comment]
blocked by https://github.com/openshift/release/pull/21776

**Comment by zshi-redhat** [comment]
@pliurh  Do we have auto script for this version change or did you do that manually (update the version in base manifest and code, then re-generate bundles)?

**Comment by pliurh** [comment]
> @pliurh Do we have auto script for this version change or did you do that manually (update the version in base manifest and code, then re-generate bundles)?

I did it manually.

**Pull request merged**
