### PR TITLE
Include openstack commits downstream

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This PR cherry-picks the following commits from upstream:

[openstack: move metadata fetch under daemon writer and reduce runs ](https://github.com/k8snetworkplumbingwg/sriov-network-operator/commit/a8465639f151c6e2e13cd7b7e0bbbedf6d630af1)
[virtual/openstack: configure VFIO with NIOMMU by default](https://github.com/k8snetworkplumbingwg/sriov-network-operator/commit/db5da317cb4b4fc39db2d22752dd9e2d19b71626)
[Vendor hashicorp/go-retryablehttp deps](https://github.com/k8snetworkplumbingwg/sriov-network-operator/commit/e31b2d02dd33e89f174301d865d204843ebf6369)
[openstack: include support to metadata service](https://github.com/k8snetworkplumbingwg/sriov-network-operator/commit/03d465ea11fe1319348a0e2df3ea0462c399b598)

### CODE REVIEW

**Comment by EmilienM** [comment]
> /test e2e-openstack-nfv-experimental

FYI this will fail until we get https://github.com/openshift/release/pull/26968/commits/e4cd45fdbc5dc7ad7b65cb7e3de0244d07867f61

**Comment by EmilienM** [comment]
/retest
Looking at the logs, it's like the metadata PR was not included...
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_sriov-network-operator/642/pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv-experimental/1504187569263349760/artifacts/e2e-openstack-nfv-experimental/gather-extra/artifacts/pods/openshift-sriov-network-operator_sriov-network-config-daemon-qwc5p_sriov-network-config-daemon.log

I'm wondering if that's because the image failed to build somehow, and it fallback on a snapshot.

**Comment by EmilienM** [comment]
weird, this happens again in a new /retest:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_sriov-network-operator/642/pull-ci-openshift-sriov-network-operator-master-e2e-openstack-nfv-experimental/1504251510886764544/artifacts/e2e-openstack-nfv-experimental/gather-extra/artifacts/pods/openshift-sriov-network-operator_sriov-network-config-daemon-pjd2s_sriov-network-config-daemon.log

@bn222 @SchSeba could you please help on this one?

Our e2e-openstack-nfv-experimental job is supposed to deploy the SR-IOV components built from this PR, look: https://steps.ci.openshift.org/workflow/openshift-e2e-openstack-nfv-experimental

**Comment by EmilienM** [comment]
/lgtm
all green :)

Nice job @MaysaMacedo

**Comment by EmilienM** [comment]
@pliurh wanted to have one big PR for all backports: https://github.com/openshift/sriov-network-operator/pull/644

/close

**Comment by MaysaMacedo** [comment]
Backported here https://github.com/openshift/sriov-network-operator/pull/644

**Pull request closed without merging**
