### PR TITLE
OCPBUGS-22709: [release-4.13] virtual: get real PCI address for each device found

### PR DESCRIPTION
**Pull request by EmilienM**
- Update utils and create interface for better unit tests implementation
- virtual: get real PCI address for each device found
- utils_virtual: unit tests
- Add Virtio 1.0 network device as supported
- [downstream-only] Support RH Virtio 1.0 network device

### CODE REVIEW

**Comment by EmilienM** [comment]
@zeeke I'm not sure I did this correctly, but this is a clean backport; I had to add one cherry-pick to make this clean.

**Comment by zeeke** [comment]
/label backport-risk-assessed

@SchSeba We had to partially backport:
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/365

Please, take a look and let me know if it looks consistent to you

**Comment by EmilienM** [comment]
Waiting on @ZivGreenberg to test the fix on 4.14.

**Comment by EmilienM** [comment]
who can cherry-pick-approve it?

**Comment by zeeke** [comment]
> who can cherry-pick-approve it?

@zhaozhanqi please, take a look

**Pull request merged**
