### PR TITLE
Downstream Sync 06-05

### PR DESCRIPTION
**Pull request by zeeke**
Cherry-pick with no conflicts

```
git cherry-pick a46193341cd0665ea736aec3d1506f9058632367 \
    bd6efc0380f6415f106eeda9e797a410edafb35b \
    d34800e4eb1a38552c24674d7cc2070a55cd86b6 \
    2ce10eaaf4838073ce89b607c6e5bdc23a22e9f5 \
    f55a17e111bf31f64aabe382950ead94c1ed161a \
    27f69740d30720b0ed6ed452b5111987bae1950a
```

### CODE REVIEW

**Comment by SchSeba** [comment]
/approve
/hold

@bn222 please take a look and remove the hold :)

**Comment by bn222** [comment]
@SchSeba I can't remove your hold. /lgtm

@vrindle pulling in your change too here. fyi

**Pull request merged**
